version: '1.0'

services:
  gatlingtest:
    image: mytestmvn
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SIMULATIONS=${SIMULATIONS}
    volumes:
      - ./reports:/gatling-lessons/reports