# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Performance Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: github-lessons

      - name: Run tests
        uses: actions/checkout@v3

      - name: Test Docker  
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: ".gatling-lessons/docker-compose-gatling-test.yml"
          test-container: helloworld
        env:
            CUSTOM_VARIABLE: "test"

      - name: Checkout test1
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: gpreport

      - name: Create file in dpPath
        run: echo 'This is a test' > dpPath/data.txt

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/gatling/
          keep_files: true
